environment       = "dev"
aws_region        = "eu-west-2"
owner_team        = "platform-team"
identifier_prefix = "goldenpath-dev-platform"

# VPC Discovery
vpc_name = "goldenpath-dev-15-01-26-11-vpc"

# RDS Instance Configuration
# Using t3.micro for cost efficiency in dev
instance_class        = "db.t3.micro"
engine_version        = "15.4"
allocated_storage     = 20
max_allocated_storage = 50 # Autoscaling up to 50GB

# Database Configuration
database_name   = "platform"
master_username = "platform_admin"
# Password will be generated by random_password resource if not provided

# Backup & Maintenance
backup_retention_period = 7

# Application Databases (Bounded Contexts)
application_databases = {
  keycloak = {
    database_name = "keycloak"
    username      = "keycloak_user"
  },
  backstage = {
    database_name = "backstage"
    username      = "backstage_user"
  }

  test_inventory2 = {
    database_name = "test_inventory2"
    username      = "test_inventory2_user"
  }
}
