#!/usr/bin/env python3
"""
---
id: generate_script_matrix
type: script
owner: platform-team
status: active
maturity: 2
test:
  runner: pytest
  command: "pytest -q tests/unit/test_generate_script_matrix.py"
  evidence: declared
dry_run:
  supported: true
risk_profile:
  production_impact: none
  security_risk: none
  coupling_risk: low
---
"""
import os
import sys
from pathlib import Path

# Add python lib to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'lib'))
try:
    from script_metadata import parse_header
except ImportError:
    print("❌ Failed to import script_metadata from lib/")
    sys.exit(1)

SCRIPTS_DIR = Path("scripts")
OUT = Path("docs/10-governance/SCRIPT_CERTIFICATION_MATRIX.md")

def get_meta(path: Path) -> dict:
    try:
        txt = path.read_text(encoding="utf-8", errors="replace")
        return parse_header(txt) or {}
    except Exception:
        return {}

def main() -> int:
    rows = []
    # Filter for scripts, exclude dirs and lib/
    scripts = sorted([
        p for p in SCRIPTS_DIR.glob("*")
        if p.is_file()
        and p.suffix in (".py", ".sh", ".bash")
        and p.name != "__init__.py"
    ])

    for p in scripts:
        meta = get_meta(p)

        # Safe getters for nested dicts
        dry_run = meta.get("dry_run", {}) if isinstance(meta.get("dry_run"), dict) else {}
        test = meta.get("test", {}) if isinstance(meta.get("test"), dict) else {}
        risk = meta.get("risk_profile", {}) if isinstance(meta.get("risk_profile"), dict) else {}

        rows.append({
            "path": str(p),
            "id": meta.get("id", "MISSING"),
            "owner": meta.get("owner", "MISSING"),
            "maturity": meta.get("maturity", "0"),
            "dry_run": dry_run.get("supported", False),
            "test_runner": test.get("runner", "MISSING"),
            "evidence": test.get("evidence", "MISSING"),
            "prod_impact": risk.get("production_impact", "MISSING"),
        })

    OUT.parent.mkdir(parents=True, exist_ok=True)

    md = []
    md.append("---")
    md.append("id: SCRIPT_CERTIFICATION_MATRIX")
    md.append("title: Script Certification Matrix")
    md.append("type: report")
    md.append("---")
    md.append("")
    md.append("<!-- AUTO-GENERATED BY scripts/generate_script_matrix.py -->")
    md.append("# Script Certification Matrix")
    md.append(f"**Total Scripts**: {len(rows)}\n")
    md.append("| Script | ID | Owner | Maturity | Dry-run | Test Runner | Evidence | Prod Impact |")
    md.append("|---|---|---|---:|---:|---|---|---|")

    for r in rows:
        # Format booleans nicely
        dry_run_icon = "✅" if r['dry_run'] is True else "🚫"

        # Format maturity
        mat = str(r['maturity'])
        if mat == "3": mat = "⭐⭐⭐ 3"
        elif mat == "2": mat = "⭐⭐ 2"
        elif mat == "1": mat = "⭐ 1"
        else: mat = "0"

        md.append(f"| `{r['path']}` | `{r['id']}` | `{r['owner']}` | {mat} | {dry_run_icon} | `{r['test_runner']}` | `{r['evidence']}` | `{r['prod_impact']}` |")

    md.append("\n*Generated automatically by CI. Do not edit manually.*")

    OUT.write_text("\n".join(md) + "\n", encoding="utf-8")
    print(f"[matrix] wrote {OUT}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
