import os
import yaml
import glob
from collections import defaultdict

WORKFLOW_DIR = ".github/workflows"
OUTPUT_FILE = "ci-workflows/CI_WORKFLOWS.md"

# Taxonomy mapping: matches workflow usage to categories
CATEGORY_MAP = {
    "Guardrails / Policy (PR)": ["guardrails", "policy", "lint", "check", "validation", "freshness", "pre-commit"],
    "Terraform Plan": ["plan", "checks"],
    "Terraform Apply": ["apply", "update"],
    "Bootstrap / Tooling": ["bootstrap", "backstage", "scaffold", "registry"],
    "Teardown / Recovery": ["teardown", "cleanup", "unlock", "recovery"],
    "Ops / Maintenance": ["orphan", "maintenance"]
}

def get_category(name):
    lower_name = name.lower()
    for category, keywords in CATEGORY_MAP.items():
        if any(k in lower_name for k in keywords):
            return category
    return "Uncategorized"

def parse_workflows():
    workflows = []
    for file_path in glob.glob(f"{WORKFLOW_DIR}/*.yml") + glob.glob(f"{WORKFLOW_DIR}/*.yaml"):
        with open(file_path, 'r') as f:
            try:
                # Read raw content to find Owner comment since YAML parser skips comments
                raw_content = f.read()
                owner = "platform" # default
                for line in raw_content.splitlines():
                    if line.startswith("# Owner:"):
                        owner = line.split(":", 1)[1].strip()
                        break
                
                # Parse YAML
                data = yaml.safe_load(raw_content)
                if not data or 'name' not in data:
                    continue
                
                name = data['name']
                category = get_category(name)
                
                triggers = []
                if 'on' in data:
                    if isinstance(data['on'], dict):
                        triggers = list(data['on'].keys())
                    elif isinstance(data['on'], list):
                        triggers = data['on']
                    elif isinstance(data['on'], str):
                        triggers = [data['on']]
                
                inputs = []
                if 'workflow_dispatch' in data.get('on', {}) and data['on']['workflow_dispatch']:
                     inputs = list(data['on']['workflow_dispatch'].get('inputs', {}).keys())

                workflows.append({
                    "name": name,
                    "file": os.path.basename(file_path),
                    "category": category,
                    "owner": owner,
                    "triggers": triggers,
                    "inputs": inputs
                })
            except Exception as e:
                print(f"Skipping {file_path}: {e}")
    return workflows

def generate_ascii_tree(workflows_by_category):
    lines = ["```text", "CI Workflows (GitHub Actions)", ""]
    
    sorted_categories = sorted(workflows_by_category.keys())
    
    for i, category in enumerate(sorted_categories):
        is_last_cat = (i == len(sorted_categories) - 1)
        prefix = "└─" if is_last_cat else "├─"
        lines.append(f"{prefix} {category}")
        
        items = sorted(workflows_by_category[category], key=lambda x: x['name'])
        for j, wf in enumerate(items):
            is_last_item = (j == len(items) - 1)
            sub_prefix = "   └─" if is_last_item else "   ├─"
            # Use pipe prefix if not last category to continue the line down
            if not is_last_cat:
                sub_prefix = "│" + sub_prefix
            else:
                sub_prefix = " " + sub_prefix
            
            lines.append(f"{sub_prefix} {wf['name']}")
        
        if not is_last_cat:
            lines.append("│")
    
    lines.append("```")
    return "\n".join(lines)

def generate_markdown(workflows):
    # Group by category
    by_category = defaultdict(list)
    for wf in workflows:
        by_category[wf['category']].append(wf)
    
    content = [
        "---",
        "id: CI_WORKFLOWS",
        "title: CI Workflows Index (Auto-Generated)",
        "type: documentation",
        "owner: platform-team",
        "status: active",
        "last_updated: 2026-01-06",
        "---",
        "",
        "# CI Workflows Index (Auto-Generated)",
        "",
        "> **Auto-Generated**: This file is generated by `scripts/generate_workflow_index.py`.",
        "",
        "## Visualize",
        "",
        generate_ascii_tree(by_category),
        "",
        "---",
        ""
    ]
    
    # Detailed sections
    for category in sorted(by_category.keys()):
        content.append(f"## {category}")
        content.append("")
        
        for wf in sorted(by_category[category], key=lambda x: x['name']):
            content.append(f"### {wf['name']}")
            content.append(f"- **File**: `{wf['file']}`")
            content.append(f"- **Owner**: {wf['owner']}")
            content.append(f"- **Triggers**: {', '.join(wf['triggers'])}")
            if wf['inputs']:
                content.append(f"- **Inputs**: {', '.join(wf['inputs'])}")
            content.append("")
            
    return "\n".join(content)

if __name__ == "__main__":
    wfs = parse_workflows()
    md = generate_markdown(wfs)
    with open(OUTPUT_FILE, "w") as f:
        f.write(md)
    print(f"✅ Generated {OUTPUT_FILE} with {len(wfs)} workflows.")
